language: ruby
rvm:
  - 2.1
install: gem install jekyll && gem install s3_website
cache: bundler
script: 
  - bundle install
  - bundle exec jekyll build
  - bundle exec ALGOLIA_API_KEY=$ALGOLIA_API_KEY jekyll algolia push
after_success: s3_website push
