language: ruby
rvm:
  - 2.1  

before_install:
  - nvm install 6.0
install:
  - gem install jekyll
  - gem install s3_website
script:
  - if [ "$TRAVIS_PULL_REQUEST" = false ]; then export bucket_name="developer.avalara.com"; else export bucket_name="ci.developer.avalara.com"; fi
  - echo $bucket_name
  - npm install
  - bundle install
  - npm run build && bundle exec jekyll build
after_success:
  - if [ -n "$ALGOLIA_API_KEY" ]; then bundle exec jekyll algolia push; fi
  - echo $TRAVIS_BRANCH
deploy:
  # deploy master to s3
  - provider: script
    skip_cleanup: true
    script: 
      - s3_website push
    on:
      branch: master
  # deploy master to production
  - provider: script
    all_branches: true
    script: echo "hi"
    on:
      condition: "$TRAVIS_BRANCH != master"
