language: ruby
rvm:
  - 2.1

before_install:
  - nvm install 6.0
install:
  - gem install jekyll
  - gem install s3_website
script:
  - npm install
  - bundle install
  - npm run build && bundle exec jekyll build
after_success:
  - if [ -n "$ALGOLIA_API_KEY" ]; then bundle exec jekyll algolia push; fi
  - if [ -n "$secret_key" ] && [ "$TRAVIS_BRANCH" == "master" ]; then bucket_name=developer.avalara.com s3_website push; fi

deploy:
  # deploy none master to production
  - provider: script
    script: echo "hi"
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH != master"