language: ruby
rvm:
  - 2.1  
before_install:
  - nvm install 6.0
install:
  - gem install jekyll
  - gem install s3_website
# before_script:
#   - npm install
#   - bundle install
script:
  - npm install
  - bundle install
  - npm run build && bundle exec jekyll build
after_success:
  - java -version
  - if [ -n "$secret_key" ] && [ "$TRAVIS_BRANCH" == "master" ]; then s3_website push --verbose ; fi
  - if [ -n "$ALGOLIA_API_KEY" ]; then bundle exec jekyll algolia push; fi
