language: node_js
node_js:
  - 6.0
before_install:
  - rvm install 2.2.2
install: gem install jekyll && gem install s3_website
cache: bundler
before_script:
  - npm install
  - npm run prebuild:deploy
  - npm run build:deploy
script: 
  - bundle install
  - bundle exec jekyll build
  - if [ -n "$ALGOLIA_API_KEY" ]; then bundle exec jekyll algolia push; fi
after_success: 
  - if [ -n "$secret_key" ]; then s3_website push; fi
