language: ruby
rvm:
  - 2.1
before_install:
  - nvm install 6.0
install:
  - gem install jekyll
  - gem install s3_website
before_script:
  - npm install
  - bundle install
script:
  # - npm test
after_success:
  - if [ -n "$ALGOLIA_API_KEY" ]; then bundle exec jekyll algolia push; fi
  - if [ -n "$secret_key" ]; then s3_website push; fi
