language: ruby
rvm:
  - 2.1
install: gem install jekyll && gem install s3_website
cache: bundler
script: 
  - bundle install
  - bundle exec jekyll build
  - ALGOLIA_API_KEY=$ALGOLIA_API_KEY bundle exec jekyll algolia push
after_success: s3_website push
