language: ruby
rvm:
  - 2.1
before_install:
  - nvm install 6.0
install: gem install jekyll && gem install s3_website
cache: bundler
before_script:
  - npm install
  - node-sass _sass/style.scss css/style.css
script: 
  - echo bundle
  - bundle install
  - bundle exec jekyll build
  - if [ -n "$ALGOLIA_API_KEY" ]; then bundle exec jekyll algolia push; fi
after_success: 
  - if [ -n "$secret_key" ]; then s3_website push; fi
